version: '3'

services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:latest
    restart: always
    volumes:
      - ./redis-master-1.conf:/etc/redis/redis.conf
      - ./redis-master-1-data:/data
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes
    ports:
      - "7001:7001"
    networks:
      - redis-cluster

  redis-master-2:
    container_name: redis-master-2
    image: redis:latest
    restart: always
    volumes:
      - ./redis-master-2.conf:/etc/redis/redis.conf
      - ./redis-master-2-data:/data
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes
    networks:
      - redis-cluster

  redis-master-3:
    container_name: redis-master-3
    image: redis:latest
    restart: always
    volumes:
      - ./redis-master-3.conf:/etc/redis/redis.conf
      - ./redis-master-3-data:/data
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes
    networks:
      - redis-cluster
